### PR TITLE
added euler totient function

### LINKED ISSUE #3: Add Euler's Totient Function
Create Euler's Totient Function with detailed comments

### PR DESCRIPTION
**Pull request by ritwikchakraborty123**
#3

### CODE REVIEW

**Comment by imrahul361** [comment]
Can you Add all euler's totient function without and with Sieve and also optimised euler's totient function.
All the 3 approaches. @ritwikchakraborty123

**Comment by ritwikchakraborty123** [comment]
Ok can you raise one more issue for that...it will be helpful for me to gather more PR

**Comment by imrahul361** [comment]
No It's a same Issue so it will be better to have it in single PR. 
we have other issues @ritwikchakraborty123

**Comment by ritwikchakraborty123** [comment]
Ok give me some time ...I will make a pr soon

**Review by imrahul361 — APPROVED** [review]

**Pull request merged**
