### PR TITLE
KMP Algorithm added

### LINKED ISSUE #1: Add KMP Algorithm
Create a Function for KMP pattern matching algorithm with proper detailed Comment

### PR DESCRIPTION
**Pull request by codewdhruv**
fixed #1

### CODE REVIEW

**Comment by imrahul361** [comment]
Single File with implementation and Comment how the function and each loops are working 
Review properly. @dhrubajyoti89
**Don't add Read.md**

**Comment by codewdhruv** [comment]
@imrahul361 do i need to add the main implementation as well?

**Comment by imrahul361** [comment]
You are not commenting properly on the working.
Go and Learn about this Algorithm before make new PR on it.
@dhrubajyoti89 
**Rejecting your PR**

**Comment by codewdhruv** [comment]
i have explained the working in the readme but you didnt accept it
what comments do you expect from me in this simple two function implementation? @imrahul361

**Comment by imrahul361** [comment]
it's for the use of Beginner. The thing is that it might be easy for you but that might be difficult for someone.
I am creating this repo for beginner in Competitive Programming. @dhrubajyoti89

**Pull request closed without merging**
