### PR TITLE
squareroot_deconmposition added

### LINKED ISSUE #15: Add Square Root Decomposition
Create a function for Square Root Decomposition with Detailed Comments.

### PR DESCRIPTION
**Pull request by ritwikchakraborty123**
#15

### CODE REVIEW

**Comment by imrahul361** [comment]
I afraid it might not be the complete implementation
Create some functions to run all different tasks and call them from the main Sqrtdecomposition Function.
I think you got my Point.
@ritwikchakraborty123

**Comment by ritwikchakraborty123** [comment]
Hai I can check this?

**Comment by imrahul361** [comment]
I just want the function like platform - LeetCode or InterviewBit
Not the complete Function @ritwikchakraborty123

**Comment by ritwikchakraborty123** [comment]
You told me to implement with main function and now you are telling to just send function...I previous sent that in previous PR on same issue

**Comment by imrahul361** [comment]
> You told me to implement with main function and now you are telling to just send function...I previous sent that in previous PR on same issue

Previously, I meant to say break the function into smaller functions to do some particular tasks
I don't want the complete program just the proper functions to call it. @ritwikchakraborty123 are you getting my point?

**Comment by ritwikchakraborty123** [comment]
yes perfectly got your point

**Comment by ritwikchakraborty123** [comment]
this is one of the much easy understandable and good commented implementation

**Pull request merged**
