### PR TITLE
KMP Algorithm added

### PR DESCRIPTION
**Pull request by codewdhruv**

### CODE REVIEW

**Comment by codewdhruv** [comment]
@imrahul361 whats with this restyled bot?

**Comment by imrahul361** [comment]
First merge your current branch and push it from your master branch

**Comment by codewdhruv** [comment]
Its an issue with indentation of the code idk why @imrahul361

**Comment by imrahul361** [comment]
@dhrubajyoti89 I have remove the restyled bot and I would like to close this PR and get a new one.This time there would be any issue 
**Don't add readme.md from your side**

Also In the new PR Please add the comments to brief functionality of each loops and for what and how each Methods exactly functions. @dhrubajyoti89

**Comment by codewdhruv** [comment]
Okay

**Pull request closed without merging**
